version: '3.4'

services:
  sccsgpacalc:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 56475:3000
    command: serve -s build
