version: '3.4'

services:
  sccsgpacalc:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "npm install --silent && npm start"
