version: '3.4'

services:
  sccsgpacalc:
    image: sccsgpacalc
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["npm", "start"]
